---
# Получаем информацию о сервисах на удаленной машине
- name: CONSUL | Get service facts
  service_facts: {}

# Перечитываем конфигурацию systemd
- name: CONSUL | Reload systemd
  systemd:
    daemon_reload: true

# Перезагружаем сервис
- name: CONSUL | Restart consul
  service:
    name: consul
    state: restarted
    enabled: true

# Останавливаем сервис
- name: CONSUL | Ensure service is stopped
  service:
    name: consul
    state: stopped
  when: "'consul.service' in services"
